### ISSUE TITLE
Django 4 compatible?

### ISSUE THREAD

**Issue by byee4** [globus/django-globus-portal-framework#178]
Hello!

Curious to know if Django version can safely be bumped to the latest version (4.1.1) in requirements? 

```
python -Wa manage.py test
/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'globus_portal_framework' defines default_app_config = 'globus_portal_framework.apps.GlobusPortalFrameworkConfig'. Django now detects this configuration automatically. You can remove default_app_config.
  app_config = AppConfig.create(entry)
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
Thanks!

**Comment by NickolausDS** [comment]
Hi @byee4,

Support for Django v4.x is long overdue and we'll try to get to this soon. No listed changes in Django v4 affect DGPF and anecdotally I've tested v4 without issues, so you'll probably be fine. If you prefer to wait for confirmation, we'll list any notes in the changelog when support is added.

**Comment by byee4** [comment]
Got it, thanks again for clarifying!
