### ISSUE TITLE
excluding a single field from search space?

### ISSUE THREAD

**Issue by byee4** [globus/django-globus-portal-framework#210]
Hi, 

I am trying to modify the search index such that the query will only return objects that match certain fields in my index. For example, if my index contains a list of subjects, how would I use filters to ensure that searching for "`subject1`" will _only_ return the first entry, excluding "`associated_subjects`" from the searchable space?

I believe it is possible to use filters to perform the opposite: with a filter, perform a search query using _only_ the "`associated_subjects`" field. But I don't know if it's possible to exclude only "`associated_subjects`" and search among `title`, `tags`, etc.

```
{
  "ingest_type": "GMetaList",
  "ingest_data": {
    "gmeta": [
      {
        "id": "metadata",
        "subject": "subject1",
        "visible_to": [
          "public"
        ],
        "content": {
          "title": "subject1",
          "tags": [
            "subject1",
          ],
          "associated_subjects": [
          	"subject1",
          	"subject2"
          ]
	}
      },
      {
        "id": "metadata",
        "subject": "subject2",
        "visible_to": [
          "public"
        ],
        "content": {
          "title": "subject2",
          "tags": [
            "subject2",
          ],
          "associated_subjects": [
          	"subject1",
          	"subject2"
          ]
	}
      }
    ]
  }
}
```

**Comment by NickolausDS** [comment]
Maybe you were already making use of this feature, but Facets defined in DGPF will generate corresponding filters by default for users to use for additional queries. You could modify [the existing example](https://django-globus-portal-framework.readthedocs.io/en/latest/tutorial/search/configuring-facets.html#configuring-facets) to do this:

```
SEARCH_INDEXES = {
    'index-slug': {
        'name': 'My Search Index',
        'uuid': 'my-search-index-uuid',
        'facets': [
          {
            'name': 'Tags',
            'field_name': 'tags'
          },
          {
            'name': 'Associated Subjects',
            'field_name': 'associated_subjects'
          },
        ],
    }
}
```

Above would give you two filtering methods on your portals left sidebar, one which filtered based on all associated subjects and another that filtered based on tags. Note that this is an 'inclusive' search and not an 'exclusive' search, the latter of which may have been more what you were interested in ("Give me all the results which DO NOT have tag 'subject2'"). 

As far as I know, the exclusive method is not possible with filters. However, it is possible with the advanced query syntax in the [Globus Search Documentation](https://docs.globus.org/api/search/query/#advanced_query_string_usage). However, the first approach above is probably more desirable from a user-experience perspective if possible.

**Comment by byee4** [comment]
Hi Nickolaus, thanks for the quick response! I'm definitely using facets, however my issue arises from when a user searches for "subject1," and both "subject1" and "subject2" are returned. This is due to "subject1" being associated with both entries. Sometimes, "subject2" is the first entry listed, which may cause confusion. In lieu of exclusive search, is it possible to rank or ensure that "subject1" is always the first entry returned?

**Comment by NickolausDS** [comment]
Yes, Globus Search supports both 'boosts' and 'sort' as options. You can see configuration for these settings in [Django Globus Portal Framework here](https://django-globus-portal-framework.readthedocs.io/en/latest/tutorial/search/search-settings-reference.html#), and more information on sort and boost can be found in the [Globus Search Documentation here](https://docs.globus.org/api/search/reference/post_query/#gsearchrequest).
