### ISSUE TITLE
DGPF fails when user didn't authenticate with Globus

### ISSUE THREAD

**Issue by jpnavarro** [globus/django-globus-portal-framework#222]
Running DGPF to search PUBLIC indexes fails if the user authenticated using other authentication methods besides Globus.

Searching public indexes should not fail like this since the SDK APIs themselves won't fail.

Running into this issue with the HPC-ED Pilot.

**Comment by NickolausDS** [comment]
@jpnavarro Can you recreate this here? https://app.shortcut.com/globus/project/13142/django-globus-portal-framework

**Comment by jpnavarro** [comment]
[Done](https://app.shortcut.com/globus/story/33487/searching-public-indexes-fails-if-the-user-has-authenticated-in-django-with-anything-besides-globus)

**Comment by NickolausDS** [comment]
@jpnavarro Thank you!
